#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fügt alle Node-Types aus der n8n Dokumentation in die Datenbank ein
"""

import sys
import io
import sqlite3
from datetime import datetime

# Fix für Windows Console Encoding
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Alle Core Nodes
CORE_NODES = [
    ("n8n-nodes-base.activationtrigger", "Activation Trigger", "Core"),
    ("n8n-nodes-base.aggregate", "Aggregate", "Core"),
    ("n8n-nodes-base.aitransform", "AI Transform", "Core"),
    ("n8n-nodes-base.code", "Code", "Core"),
    ("n8n-nodes-base.comparedatasets", "Compare Datasets", "Core"),
    ("n8n-nodes-base.compression", "Compression", "Core"),
    ("n8n-nodes-langchain.chattrigger", "Chat Trigger", "Core"),
    ("n8n-nodes-base.converttofile", "Convert to File", "Core"),
    ("n8n-nodes-base.crypto", "Crypto", "Core"),
    ("n8n-nodes-base.datatable", "Data table", "Core"),
    ("n8n-nodes-base.datetime", "Date & Time", "Core"),
    ("n8n-nodes-base.debughelper", "Debug Helper", "Core"),
    ("n8n-nodes-base.set", "Edit Fields (Set)", "Core"),
    ("n8n-nodes-base.editimage", "Edit Image", "Core"),
    ("n8n-nodes-base.emailimap", "Email Trigger (IMAP)", "Core"),
    ("n8n-nodes-base.errortrigger", "Error Trigger", "Core"),
    ("n8n-nodes-base.evaluation", "Evaluation", "Core"),
    ("n8n-nodes-base.evaluationtrigger", "Evaluation Trigger", "Core"),
    ("n8n-nodes-base.executecommand", "Execute Command", "Core"),
    ("n8n-nodes-base.executeworkflow", "Execute Sub-workflow", "Core"),
    ("n8n-nodes-base.executeworkflowtrigger", "Execute Sub-workflow Trigger", "Core"),
    ("n8n-nodes-base.executiondata", "Execution Data", "Core"),
    ("n8n-nodes-base.extractfromfile", "Extract From File", "Core"),
    ("n8n-nodes-base.filter", "Filter", "Core"),
    ("n8n-nodes-base.ftp", "FTP", "Core"),
    ("n8n-nodes-base.git", "Git", "Core"),
    ("n8n-nodes-base.graphql", "GraphQL", "Core"),
    ("n8n-nodes-langchain.guardrails", "Guardrails", "Core"),
    ("n8n-nodes-base.html", "HTML", "Core"),
    ("n8n-nodes-base.httprequest", "HTTP Request", "Core"),
    ("n8n-nodes-base.if", "If", "Core"),
    ("n8n-nodes-base.jwt", "JWT", "Core"),
    ("n8n-nodes-base.ldap", "LDAP", "Core"),
    ("n8n-nodes-base.limit", "Limit", "Core"),
    ("n8n-nodes-base.localfiletrigger", "Local File Trigger", "Core"),
    ("n8n-nodes-base.splitinbatches", "Loop Over Items (Split in Batches)", "Core"),
    ("n8n-nodes-base.manualworkflowtrigger", "Manual Trigger", "Core"),
    ("n8n-nodes-base.markdown", "Markdown", "Core"),
    ("n8n-nodes-langchain.mcptrigger", "MCP Server Trigger", "Core"),
    ("n8n-nodes-base.merge", "Merge", "Core"),
    ("n8n-nodes-base.n8n", "n8n", "Core"),
    ("n8n-nodes-base.form", "n8n Form", "Core"),
    ("n8n-nodes-base.formtrigger", "n8n Form Trigger", "Core"),
    ("n8n-nodes-base.n8ntrigger", "n8n Trigger", "Core"),
    ("n8n-nodes-base.noop", "No Operation, do nothing", "Core"),
    ("n8n-nodes-base.readwritefile", "Read/Write Files from Disk", "Core"),
    ("n8n-nodes-base.removeduplicates", "Remove Duplicates", "Core"),
    ("n8n-nodes-base.renamekeys", "Rename Keys", "Core"),
    ("n8n-nodes-langchain.respondtochat", "Respond to Chat", "Core"),
    ("n8n-nodes-base.respondtowebhook", "Respond to Webhook", "Core"),
    ("n8n-nodes-base.rssfeedread", "RSS Read", "Core"),
    ("n8n-nodes-base.rssfeedreadtrigger", "RSS Feed Trigger", "Core"),
    ("n8n-nodes-base.scheduletrigger", "Schedule Trigger", "Core"),
    ("n8n-nodes-base.sendemail", "Send Email", "Core"),
    ("n8n-nodes-base.sort", "Sort", "Core"),
    ("n8n-nodes-base.splitout", "Split Out", "Core"),
    ("n8n-nodes-base.ssetrigger", "SSE Trigger", "Core"),
    ("n8n-nodes-base.ssh", "SSH", "Core"),
    ("n8n-nodes-base.stopanderror", "Stop And Error", "Core"),
    ("n8n-nodes-base.summarize", "Summarize", "Core"),
    ("n8n-nodes-base.switch", "Switch", "Core"),
    ("n8n-nodes-base.totp", "TOTP", "Core"),
    ("n8n-nodes-base.wait", "Wait", "Core"),
    ("n8n-nodes-base.webhook", "Webhook", "Core"),
    ("n8n-nodes-base.workflowtrigger", "Workflow Trigger", "Core"),
    ("n8n-nodes-base.xml", "XML", "Core"),
]

# Alle Trigger Nodes
TRIGGER_NODES = [
    ("n8n-nodes-base.activecampaigntrigger", "ActiveCampaign Trigger", "Trigger"),
    ("n8n-nodes-base.acuityschedulingtrigger", "Acuity Scheduling Trigger", "Trigger"),
    ("n8n-nodes-base.affinitytrigger", "Affinity Trigger", "Trigger"),
    ("n8n-nodes-base.airtabletrigger", "Airtable Trigger", "Trigger"),
    ("n8n-nodes-base.amqptrigger", "AMQP Trigger", "Trigger"),
    ("n8n-nodes-base.asanatrigger", "Asana Trigger", "Trigger"),
    ("n8n-nodes-base.autopilottrigger", "Autopilot Trigger", "Trigger"),
    ("n8n-nodes-base.awssnstrigger", "AWS SNS Trigger", "Trigger"),
    ("n8n-nodes-base.bitbuckettrigger", "Bitbucket Trigger", "Trigger"),
    ("n8n-nodes-base.boxtrigger", "Box Trigger", "Trigger"),
    ("n8n-nodes-base.brevotrigger", "Brevo Trigger", "Trigger"),
    ("n8n-nodes-base.calendlytrigger", "Calendly Trigger", "Trigger"),
    ("n8n-nodes-base.caltrigger", "Cal Trigger", "Trigger"),
    ("n8n-nodes-base.chargebeetrigger", "Chargebee Trigger", "Trigger"),
    ("n8n-nodes-base.clickuptrigger", "ClickUp Trigger", "Trigger"),
    ("n8n-nodes-base.clockifytrigger", "Clockify Trigger", "Trigger"),
    ("n8n-nodes-base.convertkittrigger", "ConvertKit Trigger", "Trigger"),
    ("n8n-nodes-base.coppertrigger", "Copper Trigger", "Trigger"),
    ("n8n-nodes-base.crowddevtrigger", "crowd.dev Trigger", "Trigger"),
    ("n8n-nodes-base.customeriotrigger", "Customer.io Trigger", "Trigger"),
    ("n8n-nodes-base.emeliatrigger", "Emelia Trigger", "Trigger"),
    ("n8n-nodes-base.eventbritetrigger", "Eventbrite Trigger", "Trigger"),
    ("n8n-nodes-base.facebookleadadstrigger", "Facebook Lead Ads Trigger", "Trigger"),
    ("n8n-nodes-base.facebooktrigger", "Facebook Trigger", "Trigger"),
    ("n8n-nodes-base.figmatrigger", "Figma Trigger (Beta)", "Trigger"),
    ("n8n-nodes-base.flowtrigger", "Flow Trigger", "Trigger"),
    ("n8n-nodes-base.formiotrigger", "Form.io Trigger", "Trigger"),
    ("n8n-nodes-base.formstacktrigger", "Formstack Trigger", "Trigger"),
    ("n8n-nodes-base.getresponsetrigger", "GetResponse Trigger", "Trigger"),
    ("n8n-nodes-base.githubtrigger", "GitHub Trigger", "Trigger"),
    ("n8n-nodes-base.gitlabtrigger", "GitLab Trigger", "Trigger"),
    ("n8n-nodes-base.gmailtrigger", "Gmail Trigger", "Trigger"),
    ("n8n-nodes-base.googlecalendartrigger", "Google Calendar Trigger", "Trigger"),
    ("n8n-nodes-base.googledrivetrigger", "Google Drive Trigger", "Trigger"),
    ("n8n-nodes-base.googlebusinessprofiletrigger", "Google Business Profile Trigger", "Trigger"),
    ("n8n-nodes-base.googlesheetstrigger", "Google Sheets Trigger", "Trigger"),
    ("n8n-nodes-base.gumroadtrigger", "Gumroad Trigger", "Trigger"),
    ("n8n-nodes-base.helpscouttrigger", "Help Scout Trigger", "Trigger"),
    ("n8n-nodes-base.hubspottrigger", "Hubspot Trigger", "Trigger"),
    ("n8n-nodes-base.invoiceninjatrigger", "Invoice Ninja Trigger", "Trigger"),
    ("n8n-nodes-base.jiratrigger", "Jira Trigger", "Trigger"),
    ("n8n-nodes-base.jotformtrigger", "JotForm Trigger", "Trigger"),
    ("n8n-nodes-base.kafkatrigger", "Kafka Trigger", "Trigger"),
    ("n8n-nodes-base.keaptrigger", "Keap Trigger", "Trigger"),
    ("n8n-nodes-base.kobotoolboxtrigger", "KoboToolbox Trigger", "Trigger"),
    ("n8n-nodes-base.lemlisttrigger", "Lemlist Trigger", "Trigger"),
    ("n8n-nodes-base.lineartrigger", "Linear Trigger", "Trigger"),
    ("n8n-nodes-base.lonescaletrigger", "LoneScale Trigger", "Trigger"),
    ("n8n-nodes-base.mailchimptrigger", "Mailchimp Trigger", "Trigger"),
    ("n8n-nodes-base.mailerlitetrigger", "MailerLite Trigger", "Trigger"),
    ("n8n-nodes-base.mailjettrigger", "Mailjet Trigger", "Trigger"),
    ("n8n-nodes-base.mautictrigger", "Mautic Trigger", "Trigger"),
    ("n8n-nodes-base.microsoftonedrivetrigger", "Microsoft OneDrive Trigger", "Trigger"),
    ("n8n-nodes-base.microsoftoutlooktrigger", "Microsoft Outlook Trigger", "Trigger"),
    ("n8n-nodes-base.microsoftteamstrigger", "Microsoft Teams Trigger", "Trigger"),
    ("n8n-nodes-base.mqtttrigger", "MQTT Trigger", "Trigger"),
    ("n8n-nodes-base.netlifytrigger", "Netlify Trigger", "Trigger"),
    ("n8n-nodes-base.notiontrigger", "Notion Trigger", "Trigger"),
    ("n8n-nodes-base.onfleettrigger", "Onfleet Trigger", "Trigger"),
    ("n8n-nodes-base.paypaltrigger", "PayPal Trigger", "Trigger"),
    ("n8n-nodes-base.pipedrivetrigger", "Pipedrive Trigger", "Trigger"),
    ("n8n-nodes-base.postgrestrigger", "Postgres Trigger", "Trigger"),
    ("n8n-nodes-base.postmarktrigger", "Postmark Trigger", "Trigger"),
    ("n8n-nodes-base.pushcuttrigger", "Pushcut Trigger", "Trigger"),
    ("n8n-nodes-base.rabbitmqtrigger", "RabbitMQ Trigger", "Trigger"),
    ("n8n-nodes-base.redistrigger", "Redis Trigger", "Trigger"),
    ("n8n-nodes-base.salesforcetrigger", "Salesforce Trigger", "Trigger"),
    ("n8n-nodes-base.seatabletrigger", "SeaTable Trigger", "Trigger"),
    ("n8n-nodes-base.shopifytrigger", "Shopify Trigger", "Trigger"),
    ("n8n-nodes-base.slacktrigger", "Slack Trigger", "Trigger"),
    ("n8n-nodes-base.stravatrigger", "Strava Trigger", "Trigger"),
    ("n8n-nodes-base.stripetrigger", "Stripe Trigger", "Trigger"),
    ("n8n-nodes-base.surveymonkeytrigger", "SurveyMonkey Trigger", "Trigger"),
    ("n8n-nodes-base.taigatrigger", "Taiga Trigger", "Trigger"),
    ("n8n-nodes-base.telegramtrigger", "Telegram Trigger", "Trigger"),
    ("n8n-nodes-base.thehive5trigger", "TheHive 5 Trigger", "Trigger"),
    ("n8n-nodes-base.thehivetrigger", "TheHive Trigger", "Trigger"),
    ("n8n-nodes-base.toggltrigger", "Toggl Trigger", "Trigger"),
    ("n8n-nodes-base.trellotrigger", "Trello Trigger", "Trigger"),
    ("n8n-nodes-base.twiliotrigger", "Twilio Trigger", "Trigger"),
    ("n8n-nodes-base.typeformtrigger", "Typeform Trigger", "Trigger"),
    ("n8n-nodes-base.venafitlsprotectcloudtrigger", "Venafi TLS Protect Cloud Trigger", "Trigger"),
    ("n8n-nodes-base.ciscowebextrigger", "Webex by Cisco Trigger", "Trigger"),
    ("n8n-nodes-base.webflowtrigger", "Webflow Trigger", "Trigger"),
    ("n8n-nodes-base.whatsapptrigger", "WhatsApp Trigger", "Trigger"),
    ("n8n-nodes-base.wisetrigger", "Wise Trigger", "Trigger"),
    ("n8n-nodes-base.woocommercetrigger", "WooCommerce Trigger", "Trigger"),
    ("n8n-nodes-base.workabletrigger", "Workable Trigger", "Trigger"),
    ("n8n-nodes-base.wufootrigger", "Wufoo Trigger", "Trigger"),
    ("n8n-nodes-base.zendesktrigger", "Zendesk Trigger", "Trigger"),
]

# Alle LangChain/Cluster Nodes
LANGCHAIN_NODES = [
    ("n8n-nodes-langchain.agent", "AI Agent", "LangChain"),
    ("n8n-nodes-langchain.chainllm", "Basic LLM Chain", "LangChain"),
    ("n8n-nodes-langchain.chainretrievalqa", "Question and Answer Chain", "LangChain"),
    ("n8n-nodes-langchain.chainsummarization", "Summarization Chain", "LangChain"),
    ("n8n-nodes-langchain.information-extractor", "Information Extractor", "LangChain"),
    ("n8n-nodes-langchain.text-classifier", "Text Classifier", "LangChain"),
    ("n8n-nodes-langchain.sentimentanalysis", "Sentiment Analysis", "LangChain"),
    ("n8n-nodes-langchain.code", "LangChain Code", "LangChain"),
    ("n8n-nodes-langchain.vectorstoreinmemory", "Simple Vector Store", "LangChain"),
    ("n8n-nodes-langchain.vectorstoremilvus", "Milvus Vector Store", "LangChain"),
    ("n8n-nodes-langchain.vectorstoremongodbatlas", "MongoDB Atlas Vector Store", "LangChain"),
    ("n8n-nodes-langchain.vectorstorepgvector", "PGVector Vector Store", "LangChain"),
    ("n8n-nodes-langchain.vectorstorepinecone", "Pinecone Vector Store", "LangChain"),
    ("n8n-nodes-langchain.vectorstoreqdrant", "Qdrant Vector Store", "LangChain"),
    ("n8n-nodes-langchain.vectorstoreredis", "Redis Vector Store", "LangChain"),
    ("n8n-nodes-langchain.vectorstoresupabase", "Supabase Vector Store", "LangChain"),
    ("n8n-nodes-langchain.vectorstoreweaviate", "Weaviate Vector Store", "LangChain"),
    ("n8n-nodes-langchain.vectorstorezep", "Zep Vector Store", "LangChain"),
]

# App Nodes - COMPLETE LIST von n8n Dokumentation
APP_NODES = [
    ("n8n-nodes-base.actionnetwork", "Action Network", "App"),
    ("n8n-nodes-base.activecampaign", "ActiveCampaign", "App"),
    ("n8n-nodes-base.adalo", "Adalo", "App"),
    ("n8n-nodes-base.affinity", "Affinity", "App"),
    ("n8n-nodes-base.agilecrm", "Agile CRM", "App"),
    ("n8n-nodes-base.airtable", "Airtable", "App"),
    ("n8n-nodes-base.airtop", "Airtop", "App"),
    ("n8n-nodes-base.amqp", "AMQP Sender", "App"),
    ("n8n-nodes-langchain.anthropic", "Anthropic", "App"),
    ("n8n-nodes-base.apitemplateio", "APITemplate.io", "App"),
    ("n8n-nodes-base.asana", "Asana", "App"),
    ("n8n-nodes-base.autopilot", "Autopilot", "App"),
    ("n8n-nodes-base.awscertificatemanager", "AWS Certificate Manager", "App"),
    ("n8n-nodes-base.awscognito", "AWS Cognito", "App"),
    ("n8n-nodes-base.awscomprehend", "AWS Comprehend", "App"),
    ("n8n-nodes-base.awsdynamodb", "AWS DynamoDB", "App"),
    ("n8n-nodes-base.awselb", "AWS Elastic Load Balancing", "App"),
    ("n8n-nodes-base.awsiam", "AWS IAM", "App"),
    ("n8n-nodes-base.awslambda", "AWS Lambda", "App"),
    ("n8n-nodes-base.awsrekognition", "AWS Rekognition", "App"),
    ("n8n-nodes-base.awss3", "AWS S3", "App"),
    ("n8n-nodes-base.awsses", "AWS SES", "App"),
    ("n8n-nodes-base.awssns", "AWS SNS", "App"),
    ("n8n-nodes-base.awssqs", "AWS SQS", "App"),
    ("n8n-nodes-base.awstextract", "AWS Textract", "App"),
    ("n8n-nodes-base.awstranscribe", "AWS Transcribe", "App"),
    ("n8n-nodes-base.azurecosmosdb", "Azure Cosmos DB", "App"),
    ("n8n-nodes-base.azurestorage", "Azure Storage", "App"),
    ("n8n-nodes-base.bamboohr", "BambooHR", "App"),
    ("n8n-nodes-base.bannerbear", "Bannerbear", "App"),
    ("n8n-nodes-base.baserow", "Baserow", "App"),
    ("n8n-nodes-base.beeminder", "Beeminder", "App"),
    ("n8n-nodes-base.bitly", "Bitly", "App"),
    ("n8n-nodes-base.bitwarden", "Bitwarden", "App"),
    ("n8n-nodes-base.box", "Box", "App"),
    ("n8n-nodes-base.brandfetch", "Brandfetch", "App"),
    ("n8n-nodes-base.brevo", "Brevo", "App"),
    ("n8n-nodes-base.bubble", "Bubble", "App"),
    ("n8n-nodes-base.chargebee", "Chargebee", "App"),
    ("n8n-nodes-base.circleci", "CircleCI", "App"),
    ("n8n-nodes-base.ciscowebex", "Webex by Cisco", "App"),
    ("n8n-nodes-base.clearbit", "Clearbit", "App"),
    ("n8n-nodes-base.clickup", "ClickUp", "App"),
    ("n8n-nodes-base.clockify", "Clockify", "App"),
    ("n8n-nodes-base.cloudflare", "Cloudflare", "App"),
    ("n8n-nodes-base.cockpit", "Cockpit", "App"),
    ("n8n-nodes-base.coda", "Coda", "App"),
    ("n8n-nodes-base.coingecko", "CoinGecko", "App"),
    ("n8n-nodes-base.contentful", "Contentful", "App"),
    ("n8n-nodes-base.convertkit", "ConvertKit", "App"),
    ("n8n-nodes-base.copper", "Copper", "App"),
    ("n8n-nodes-base.cortex", "Cortex", "App"),
    ("n8n-nodes-base.cratedb", "CrateDB", "App"),
    ("n8n-nodes-base.crowddev", "crowd.dev", "App"),
    ("n8n-nodes-base.customerio", "Customer.io", "App"),
    ("n8n-nodes-base.deepl", "DeepL", "App"),
    ("n8n-nodes-base.demio", "Demio", "App"),
    ("n8n-nodes-base.dhl", "DHL", "App"),
    ("n8n-nodes-base.discord", "Discord", "App"),
    ("n8n-nodes-base.discourse", "Discourse", "App"),
    ("n8n-nodes-base.disqus", "Disqus", "App"),
    ("n8n-nodes-base.drift", "Drift", "App"),
    ("n8n-nodes-base.dropbox", "Dropbox", "App"),
    ("n8n-nodes-base.dropcontact", "Dropcontact", "App"),
    ("n8n-nodes-base.egoi", "E-goi", "App"),
    ("n8n-nodes-base.elasticsearch", "Elasticsearch", "App"),
    ("n8n-nodes-base.elasticsecurity", "Elastic Security", "App"),
    ("n8n-nodes-base.emelia", "Emelia", "App"),
    ("n8n-nodes-base.erpnext", "ERPNext", "App"),
    ("n8n-nodes-base.facebookgraphapi", "Facebook Graph API", "App"),
    ("n8n-nodes-base.filemaker", "FileMaker", "App"),
    ("n8n-nodes-base.flow", "Flow", "App"),
    ("n8n-nodes-base.freshdesk", "Freshdesk", "App"),
    ("n8n-nodes-base.freshservice", "Freshservice", "App"),
    ("n8n-nodes-base.freshworkscrm", "Freshworks CRM", "App"),
    ("n8n-nodes-base.getresponse", "GetResponse", "App"),
    ("n8n-nodes-base.ghost", "Ghost", "App"),
    ("n8n-nodes-base.github", "GitHub", "App"),
    ("n8n-nodes-base.gitlab", "GitLab", "App"),
    ("n8n-nodes-base.gmail", "Gmail", "App"),
    ("n8n-nodes-base.gong", "Gong", "App"),
    ("n8n-nodes-base.googleads", "Google Ads", "App"),
    ("n8n-nodes-base.googleanalytics", "Google Analytics", "App"),
    ("n8n-nodes-base.googlebigquery", "Google BigQuery", "App"),
    ("n8n-nodes-base.googlebooks", "Google Books", "App"),
    ("n8n-nodes-base.googlebusinessprofile", "Google Business Profile", "App"),
    ("n8n-nodes-base.googlecalendar", "Google Calendar", "App"),
    ("n8n-nodes-base.googlechat", "Google Chat", "App"),
    ("n8n-nodes-base.googlecloudfirestore", "Google Cloud Firestore", "App"),
    ("n8n-nodes-base.googlecloudnaturallanguage", "Google Cloud Natural Language", "App"),
    ("n8n-nodes-base.googlecloudrealtimedatabase", "Google Cloud Realtime Database", "App"),
    ("n8n-nodes-base.googlecloudstorage", "Google Cloud Storage", "App"),
    ("n8n-nodes-base.googlecontacts", "Google Contacts", "App"),
    ("n8n-nodes-base.googledocs", "Google Docs", "App"),
    ("n8n-nodes-base.googledrive", "Google Drive", "App"),
    ("n8n-nodes-langchain.googlegemini", "Google Gemini", "App"),
    ("n8n-nodes-base.googleperspective", "Google Perspective", "App"),
    ("n8n-nodes-base.googlesheets", "Google Sheets", "App"),
    ("n8n-nodes-base.googleslides", "Google Slides", "App"),
    ("n8n-nodes-base.googletasks", "Google Tasks", "App"),
    ("n8n-nodes-base.googletranslate", "Google Translate", "App"),
    ("n8n-nodes-base.gsuiteadmin", "Google Workspace Admin", "App"),
    ("n8n-nodes-base.gotify", "Gotify", "App"),
    ("n8n-nodes-base.gotowebinar", "GoToWebinar", "App"),
    ("n8n-nodes-base.grafana", "Grafana", "App"),
    ("n8n-nodes-base.grist", "Grist", "App"),
    ("n8n-nodes-base.hackernews", "Hacker News", "App"),
    ("n8n-nodes-base.halopsa", "HaloPSA", "App"),
    ("n8n-nodes-base.harvest", "Harvest", "App"),
    ("n8n-nodes-base.helpscout", "Help Scout", "App"),
    ("n8n-nodes-base.highlevel", "HighLevel", "App"),
    ("n8n-nodes-base.homeassistant", "Home Assistant", "App"),
    ("n8n-nodes-base.hubspot", "HubSpot", "App"),
    ("n8n-nodes-base.humanticai", "Humantic AI", "App"),
    ("n8n-nodes-base.hunter", "Hunter", "App"),
    ("n8n-nodes-base.intercom", "Intercom", "App"),
    ("n8n-nodes-base.invoiceninja", "Invoice Ninja", "App"),
    ("n8n-nodes-base.iterable", "Iterable", "App"),
    ("n8n-nodes-base.jenkins", "Jenkins", "App"),
    ("n8n-nodes-base.jinaai", "Jina AI", "App"),
    ("n8n-nodes-base.jira", "Jira Software", "App"),
    ("n8n-nodes-base.kafka", "Kafka", "App"),
    ("n8n-nodes-base.keap", "Keap", "App"),
    ("n8n-nodes-base.kitemaker", "Kitemaker", "App"),
    ("n8n-nodes-base.kobotoolbox", "KoboToolbox", "App"),
    ("n8n-nodes-base.lemlist", "Lemlist", "App"),
    ("n8n-nodes-base.line", "Line", "App"),
    ("n8n-nodes-base.linear", "Linear", "App"),
    ("n8n-nodes-base.lingvanex", "LingvaNex", "App"),
    ("n8n-nodes-base.linkedin", "LinkedIn", "App"),
    ("n8n-nodes-base.lonescale", "LoneScale", "App"),
    ("n8n-nodes-base.magento2", "Magento 2", "App"),
    ("n8n-nodes-base.mailcheck", "Mailcheck", "App"),
    ("n8n-nodes-base.mailchimp", "Mailchimp", "App"),
    ("n8n-nodes-base.mailerlite", "MailerLite", "App"),
    ("n8n-nodes-base.mailgun", "Mailgun", "App"),
    ("n8n-nodes-base.mailjet", "Mailjet", "App"),
    ("n8n-nodes-base.mandrill", "Mandrill", "App"),
    ("n8n-nodes-base.marketstack", "marketstack", "App"),
    ("n8n-nodes-base.matrix", "Matrix", "App"),
    ("n8n-nodes-base.mattermost", "Mattermost", "App"),
    ("n8n-nodes-base.mautic", "Mautic", "App"),
    ("n8n-nodes-base.medium", "Medium", "App"),
    ("n8n-nodes-base.messagebird", "MessageBird", "App"),
    ("n8n-nodes-base.metabase", "Metabase", "App"),
    ("n8n-nodes-base.microsoftdynamicscrm", "Microsoft Dynamics CRM", "App"),
    ("n8n-nodes-base.microsoftentra", "Microsoft Entra ID", "App"),
    ("n8n-nodes-base.microsoftexcel", "Microsoft Excel 365", "App"),
    ("n8n-nodes-base.microsoftgraphsecurity", "Microsoft Graph Security", "App"),
    ("n8n-nodes-base.microsoftonedrive", "Microsoft OneDrive", "App"),
    ("n8n-nodes-base.microsoftoutlook", "Microsoft Outlook", "App"),
    ("n8n-nodes-base.microsoftsharepoint", "Microsoft SharePoint", "App"),
    ("n8n-nodes-base.microsoftsql", "Microsoft SQL", "App"),
    ("n8n-nodes-base.microsoftteams", "Microsoft Teams", "App"),
    ("n8n-nodes-base.microsofttodo", "Microsoft To Do", "App"),
    ("n8n-nodes-base.mindee", "Mindee", "App"),
    ("n8n-nodes-base.misp", "MISP", "App"),
    ("n8n-nodes-base.mistralai", "Mistral AI", "App"),
    ("n8n-nodes-base.mocean", "Mocean", "App"),
    ("n8n-nodes-base.mondaycom", "monday.com", "App"),
    ("n8n-nodes-base.mongodb", "MongoDB", "App"),
    ("n8n-nodes-base.monicacrm", "Monica CRM", "App"),
    ("n8n-nodes-base.mqtt", "MQTT", "App"),
    ("n8n-nodes-base.msg91", "MSG91", "App"),
    ("n8n-nodes-base.mysql", "MySQL", "App"),
    ("n8n-nodes-base.n8ntrainingcustomerdatastore", "Customer Datastore (n8n Training)", "App"),
    ("n8n-nodes-base.n8ntrainingcustomermessenger", "Customer Messenger (n8n Training)", "App"),
    ("n8n-nodes-base.nasa", "NASA", "App"),
    ("n8n-nodes-base.netlify", "Netlify", "App"),
    ("n8n-nodes-base.netscaleradc", "Netscaler ADC", "App"),
    ("n8n-nodes-base.nextcloud", "Nextcloud", "App"),
    ("n8n-nodes-base.nocodb", "NocoDB", "App"),
    ("n8n-nodes-base.notion", "Notion", "App"),
    ("n8n-nodes-base.npm", "npm", "App"),
    ("n8n-nodes-base.odoo", "Odoo", "App"),
    ("n8n-nodes-base.okta", "Okta", "App"),
    ("n8n-nodes-base.onesimpleapi", "One Simple API", "App"),
    ("n8n-nodes-base.onfleet", "Onfleet", "App"),
    ("n8n-nodes-langchain.openai", "OpenAI", "App"),
    ("n8n-nodes-base.openthesaurus", "OpenThesaurus", "App"),
    ("n8n-nodes-base.openweathermap", "OpenWeatherMap", "App"),
    ("n8n-nodes-base.oracledb", "Oracle Database", "App"),
    ("n8n-nodes-base.oura", "Oura", "App"),
    ("n8n-nodes-base.paddle", "Paddle", "App"),
    ("n8n-nodes-base.pagerduty", "PagerDuty", "App"),
    ("n8n-nodes-base.paypal", "PayPal", "App"),
    ("n8n-nodes-base.peekalink", "Peekalink", "App"),
    ("n8n-nodes-langchain.perplexity", "Perplexity", "App"),
    ("n8n-nodes-base.phantombuster", "PhantomBuster", "App"),
    ("n8n-nodes-base.philipshue", "Philips Hue", "App"),
    ("n8n-nodes-base.pipedrive", "Pipedrive", "App"),
    ("n8n-nodes-base.plivo", "Plivo", "App"),
    ("n8n-nodes-base.postbin", "PostBin", "App"),
    ("n8n-nodes-base.postgres", "Postgres", "App"),
    ("n8n-nodes-base.posthog", "PostHog", "App"),
    ("n8n-nodes-base.profitwell", "ProfitWell", "App"),
    ("n8n-nodes-base.pushbullet", "Pushbullet", "App"),
    ("n8n-nodes-base.pushcut", "Pushcut", "App"),
    ("n8n-nodes-base.pushover", "Pushover", "App"),
    ("n8n-nodes-base.questdb", "QuestDB", "App"),
    ("n8n-nodes-base.quickbase", "Quick Base", "App"),
    ("n8n-nodes-base.quickbooks", "QuickBooks Online", "App"),
    ("n8n-nodes-base.quickchart", "QuickChart", "App"),
    ("n8n-nodes-base.rabbitmq", "RabbitMQ", "App"),
    ("n8n-nodes-base.raindrop", "Raindrop", "App"),
    ("n8n-nodes-base.reddit", "Reddit", "App"),
    ("n8n-nodes-base.redis", "Redis", "App"),
    ("n8n-nodes-base.rocketchat", "Rocket.Chat", "App"),
    ("n8n-nodes-base.rundeck", "Rundeck", "App"),
    ("n8n-nodes-base.s3", "S3", "App"),
    ("n8n-nodes-base.salesforce", "Salesforce", "App"),
    ("n8n-nodes-base.salesmate", "Salesmate", "App"),
    ("n8n-nodes-base.seatable", "SeaTable", "App"),
    ("n8n-nodes-base.securityscorecard", "SecurityScorecard", "App"),
    ("n8n-nodes-base.segment", "Segment", "App"),
    ("n8n-nodes-base.sendgrid", "SendGrid", "App"),
    ("n8n-nodes-base.sendy", "Sendy", "App"),
    ("n8n-nodes-base.sentryio", "Sentry.io", "App"),
    ("n8n-nodes-base.servicenow", "ServiceNow", "App"),
    ("n8n-nodes-base.sms77", "seven", "App"),
    ("n8n-nodes-base.shopify", "Shopify", "App"),
    ("n8n-nodes-base.signl4", "SIGNL4", "App"),
    ("n8n-nodes-base.slack", "Slack", "App"),
    ("n8n-nodes-base.snowflake", "Snowflake", "App"),
    ("n8n-nodes-base.splunk", "Splunk", "App"),
    ("n8n-nodes-base.spotify", "Spotify", "App"),
    ("n8n-nodes-base.stackby", "Stackby", "App"),
    ("n8n-nodes-base.storyblok", "Storyblok", "App"),
    ("n8n-nodes-base.strapi", "Strapi", "App"),
    ("n8n-nodes-base.strava", "Strava", "App"),
    ("n8n-nodes-base.stripe", "Stripe", "App"),
    ("n8n-nodes-base.supabase", "Supabase", "App"),
    ("n8n-nodes-base.syncromsp", "SyncroMSP", "App"),
    ("n8n-nodes-base.taiga", "Taiga", "App"),
    ("n8n-nodes-base.tapfiliate", "Tapfiliate", "App"),
    ("n8n-nodes-base.telegram", "Telegram", "App"),
    ("n8n-nodes-base.thehive", "TheHive", "App"),
    ("n8n-nodes-base.thehive5", "TheHive 5", "App"),
    ("n8n-nodes-base.timescaledb", "TimescaleDB", "App"),
    ("n8n-nodes-base.todoist", "Todoist", "App"),
    ("n8n-nodes-base.travisci", "Travis CI", "App"),
    ("n8n-nodes-base.trello", "Trello", "App"),
    ("n8n-nodes-base.twake", "Twake", "App"),
    ("n8n-nodes-base.twilio", "Twilio", "App"),
    ("n8n-nodes-base.twist", "Twist", "App"),
    ("n8n-nodes-base.unleashedsoftware", "Unleashed Software", "App"),
    ("n8n-nodes-base.uplead", "UpLead", "App"),
    ("n8n-nodes-base.uproc", "uProc", "App"),
    ("n8n-nodes-base.uptimerobot", "UptimeRobot", "App"),
    ("n8n-nodes-base.urlscanio", "urlscan.io", "App"),
    ("n8n-nodes-base.venafitlsprotectcloud", "Venafi TLS Protect Cloud", "App"),
    ("n8n-nodes-base.venafitlsprotectdatacenter", "Venafi TLS Protect Datacenter", "App"),
    ("n8n-nodes-base.vero", "Vero", "App"),
    ("n8n-nodes-base.vonage", "Vonage", "App"),
    ("n8n-nodes-base.webflow", "Webflow", "App"),
    ("n8n-nodes-base.wekan", "Wekan", "App"),
    ("n8n-nodes-base.whatsapp", "WhatsApp Business Cloud", "App"),
    ("n8n-nodes-base.wise", "Wise", "App"),
    ("n8n-nodes-base.woocommerce", "WooCommerce", "App"),
    ("n8n-nodes-base.wordpress", "WordPress", "App"),
    ("n8n-nodes-base.twitter", "X (Formerly Twitter)", "App"),
    ("n8n-nodes-base.xero", "Xero", "App"),
    ("n8n-nodes-base.yourls", "Yourls", "App"),
    ("n8n-nodes-base.youtube", "YouTube", "App"),
    ("n8n-nodes-base.zammad", "Zammad", "App"),
    ("n8n-nodes-base.zendesk", "Zendesk", "App"),
    ("n8n-nodes-base.zohocrm", "Zoho CRM", "App"),
    ("n8n-nodes-base.zoom", "Zoom", "App"),
    ("n8n-nodes-base.zulip", "Zulip", "App"),
]


def populate_database(db_name='n8n_docs.db'):
    """Fügt alle Node-Types in die Datenbank ein"""
    conn = sqlite3.connect(db_name)
    cursor = conn.cursor()

    all_nodes = CORE_NODES + TRIGGER_NODES + LANGCHAIN_NODES + APP_NODES

    print(f"🚀 Füge {len(all_nodes)} Node-Types in die Datenbank ein...\n")

    saved = 0
    updated = 0
    errors = 0

    for node_type, display_name, category in all_nodes:
        try:
            cursor.execute('''
                INSERT OR REPLACE INTO node_types_api
                (node_type, display_name, description, version, icon, category, scraped_at)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            ''', (
                node_type,
                display_name,
                f"From n8n documentation - {category}",
                1,
                '',
                category,
                datetime.now()
            ))

            if cursor.rowcount > 0:
                saved += 1
                print(f"✓ {node_type} → {display_name}")
            else:
                updated += 1
                print(f"↻ {node_type} → {display_name} (updated)")

        except sqlite3.Error as e:
            errors += 1
            print(f"✗ {node_type}: {e}")

    conn.commit()
    conn.close()

    print(f"\n{'='*80}")
    print(f"✅ Fertig!")
    print(f"   • Neu gespeichert: {saved}")
    print(f"   • Aktualisiert: {updated}")
    print(f"   • Fehler: {errors}")
    print(f"   • Gesamt: {len(all_nodes)}")
    print(f"{'='*80}\n")


if __name__ == '__main__':
    populate_database()
